extends Node

const GAME_SET_CAMERA_LIMIT_RIGHT = 'GAME_SET_CAMERA_LIMIT_RIGHT'
const GAME_SET_SCREEN_WIDTH = 'GAME_SET_SCREEN_WIDTH'
const GAME_SET_SCREEN_HEIGHT = 'GAME_SET_SCREEN_HEIGHT'
const GAME_SET_DISPLAY_SCENE = 'GAME_SET_DISPLAY_SCENE'
const GAME_SET_CURRENT_LEVEL = 'GAME_SET_CURRENT_LEVEL'
const GAME_SET_GAME_TIME_SECONDS = 'GAME_SET_GAME_TIME_SECONDS'
const GAME_SET_BEAT_COUNT = 'GAME_SET_BEAT_COUNT'

const GAME_SET_DAY = 'GAME_SET_DAY'
const GAME_SET_STATE = 'GAME_SET_STATE'
const GAME_SET_MONEY = 'GAME_SET_MONEY'
const GAME_SET_MISSION = 'GAME_SET_MISSION'

const PLAYER_SET_HEALTH = 'PLAYER_SET_HEALTH'

const CANVAS_SET_DIMENSIONS = 'CANVAS_SET_DIMENSIONS'
const CANVAS_SET_STARTING_VECTOR = 'CANVAS_SET_STARTING_VECTOR'
const CANVAS_SET_GRID = 'CANVAS_SET_GRID'
const CANVAS_ADD_TO_GRID = 'CANVAS_ADD_TO_GRID'

const PAINT_SET_PAINT_LIST = 'PAINT_SET_PAINT_LIST'
const PAINT_SET_PAINT_INFO = 'PAINT_SET_PAINT_INFO'
const PAINT_SET_CURRENT_PAINT = 'PAINT_SET_CURRENT_PAINT'
const PAINT_ADD_COLOR = 'PAINT_ADD_COLOR'
const PAINT_REMOVE_COLOR = 'PAINT_REMOVE_COLOR'
const PAINT_SET_RANDOM_PAINTS_LIST = 'PAINT_SET_RANDOM_PAINTS_LIST'