extends Node

const GAME_SET_CAMERA_LIMIT_RIGHT = 'GAME_SET_CAMERA_LIMIT_RIGHT'
const GAME_SET_SCREEN_WIDTH = 'GAME_SET_SCREEN_WIDTH'
const GAME_SET_SCREEN_HEIGHT = 'GAME_SET_SCREEN_HEIGHT'
const GAME_SET_DISPLAY_SCENE = 'GAME_SET_DISPLAY_SCENE'
const GAME_SET_CURRENT_LEVEL = 'GAME_SET_CURRENT_LEVEL'
const GAME_SET_GAME_TIME_SECONDS = 'GAME_SET_GAME_TIME_SECONDS'
const GAME_SET_BEAT_COUNT = 'GAME_SET_BEAT_COUNT'

const GAME_SET_DAY = 'GAME_SET_DAY'
const GAME_SET_HOUR = 'GAME_SET_HOUR'
const GAME_SET_STATE = 'GAME_SET_STATE'
const GAME_SET_PROGRESS = 'GAME_SET_PROGRESS'

const DIALOGUE_SET_QUEUE = 'DIALOGUE_SET_QUEUE'
const DIALOGUE_SET_RABBIT_POSITION = 'DIALOGUE_SET_RABBIT_POSITION'
const DIALOGUE_SET_NPC_POSITION = 'DIALOGUE_SET_NPC_POSITION'
const DIALOGUE_POP_QUEUE = 'DIALOGUE_POP_QUEUE'

const DIALOGUE_SET_CRAB_DICT = 'DIALOGUE_SET_CRAB_DICT'
const DIALOGUE_INCREMENT_CRAB_DICT = 'DIALOGUE_INCREMENT_CRAB_DICT'

const DIALOGUE_SET_FATHER_DICT = 'DIALOGUE_SET_FATHER_DICT'
const DIALOGUE_INCREMENT_FATHER_DICT = 'DIALOGUE_INCREMENT_FATHER_DICT'

const CANVAS_SET_DIMENSIONS = 'CANVAS_SET_DIMENSIONS'
const CANVAS_SET_STARTING_VECTOR = 'CANVAS_SET_STARTING_VECTOR'
const CANVAS_SET_GRID = 'CANVAS_SET_GRID'
const CANVAS_ADD_TO_GRID = 'CANVAS_ADD_TO_GRID'
